version: '3.9'

services:
  web:
    build: 
      context: .
    working_dir: /main
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             gunicorn blog.wsgi:application --bind 0.0.0.0:8000"

    expose:
      - 8000
    # ports:
    #   - 8000:8000
    volumes:
      - ./main:/main
      - static_volume:/app/main/staticfiles
      - media_volume:/app/main/mediafiles
    environment:
      - DEBUG=1
      - SECRET_KEY=secret_key
      - ALLOWED_HOSTS=127.0.0.1 this_is_a_test localhost
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=needtochange
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=needtochange
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/main/staticfiles
      - ./main/mediafiles:/app/main/mediafiles
    ports:
      - 8080:80
    depends_on:
      - web
    

volumes:
  postgres_data:
  static_volume:
  media_volume: