version: '3.9'

services:
  web:
    build: 
      context: .
    restart: always
    expose:
      - 8000

    volumes:
      - static_volume:/app/main/staticfiles
      - media_volume:/app/main/mediafiles

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/app/main/staticfiles
      - media_volume:/app/main/mediafiles
    ports:
      - 80:80
    depends_on:
      - web
    
volumes:
  static_volume:
  media_volume: